### ISSUE TITLE
unexpected null datasource

### ISSUE THREAD

**Issue by nanouck** [DevOps-Nirvana/Grafana-Dashboards#3]
https://github.com/DevOps-Nirvana/Grafana-Dashboards/blob/5798060d7e9509d2ce33c66a71ee731f1611369c/kubernetes-nginx-ingress-via-prometheus.json#L181

Hi, it looks a lot of remaining `"datasource": null`, that makes trouble on my grafana 7.5.1 setup, should not they fixed?
lines 181, 273, 365, 457, 909, 1014, 1143, 1258, 1454, 1536, 1641, 1754, 1860

![image](https://user-images.githubusercontent.com/3948061/137497799-fb930c4d-c715-48f2-a891-b0da35a0a051.png)

edit the `% Success (period)` query => cf `Random Walk`
![image](https://user-images.githubusercontent.com/3948061/137497981-5dca1b84-6e27-41ad-81b7-5990984bb447.png)

**Comment by AndrewFarley** [comment]
fixed in #4 and #5
